# frozen_string_literal: true

require "sinatra/activerecord/rake"
require_relative "app"

begin
  require "rspec/core/rake_task"
  RSpec::Core::RakeTask.new(:spec)
rescue LoadError
end

task default: :spec
